<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net9.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
	<TreatWarningsAsErrors>true</TreatWarningsAsErrors>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="CsvHelper" Version="33.1.0" />
    <PackageReference Include="Hangfire.Core" Version="1.8.20" />
    <PackageReference Include="Hangfire.MissionControl" Version="0.10.0" />
    <PackageReference Include="Microsoft.Extensions.Hosting.Abstractions" Version="9.0.8" />
    <PackageReference Include="Microsoft.Extensions.Logging.Abstractions" Version="9.0.8" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\RealEstateAnalyzer.Application.Abstractions\RealEstateAnalyzer.Application.Abstractions.csproj" />
    <ProjectReference Include="..\RealEstateAnalyzer.Domain\RealEstateAnalyzer.Domain.csproj" />
  </ItemGroup>

  <ItemGroup>
    <Folder Include="BackgroundJobs\WebScraping\" />
  </ItemGroup>

</Project>
