import { MarketData, CorrelationData } from "@/models"

export const cityTrendData: { [key: string]: MarketData[] } = {
  Warszawa: [
    { month: "Sty", avgPrice: 12000, listings: 245, sales: 1890, inventory: 178, demand: 85 },
    { month: "Lut", avgPrice: 12100, listings: 262, sales: 1875, inventory: 182, demand: 87 },
    { month: "Mar", avgPrice: 12200, listings: 278, sales: 1860, inventory: 185, demand: 89 },
    { month: "Kwi", avgPrice: 12350, listings: 295, sales: 1845, inventory: 188, demand: 91 },
    { month: "Maj", avgPrice: 12450, listings: 310, sales: 1830, inventory: 192, demand: 88 },
    { month: "Cze", avgPrice: 12500, listings: 325, sales: 1815, inventory: 195, demand: 86 },
  ],
  Kraków: [
    { month: "Sty", avgPrice: 9200, listings: 195, sales: 1490, inventory: 128, demand: 82 },
    { month: "Lut", avgPrice: 9350, listings: 212, sales: 1475, inventory: 132, demand: 84 },
    { month: "Mar", avgPrice: 9500, listings: 228, sales: 1460, inventory: 135, demand: 86 },
    { month: "Kwi", avgPrice: 9650, listings: 245, sales: 1445, inventory: 138, demand: 88 },
    { month: "Maj", avgPrice: 9750, listings: 260, sales: 1430, inventory: 142, demand: 85 },
    { month: "Cze", avgPrice: 9800, listings: 275, sales: 1415, inventory: 145, demand: 83 },
  ],
  Łódź: [
    { month: "Sty", avgPrice: 6800, listings: 180, sales: 1100, inventory: 110, demand: 70 },
    { month: "Lut", avgPrice: 6850, listings: 190, sales: 1120, inventory: 115, demand: 72 },
    { month: "Mar", avgPrice: 6900, listings: 200, sales: 1150, inventory: 120, demand: 75 },
    { month: "Kwi", avgPrice: 7000, listings: 215, sales: 1180, inventory: 125, demand: 78 },
    { month: "Maj", avgPrice: 7100, listings: 225, sales: 1200, inventory: 130, demand: 76 },
    { month: "Cze", avgPrice: 7150, listings: 230, sales: 1210, inventory: 135, demand: 74 },
  ],
  Wrocław: [
    { month: "Sty", avgPrice: 7800, listings: 145, sales: 1090, inventory: 88, demand: 76 },
    { month: "Lut", avgPrice: 7850, listings: 162, sales: 1075, inventory: 92, demand: 78 },
    { month: "Mar", avgPrice: 7900, listings: 178, sales: 1060, inventory: 95, demand: 80 },
    { month: "Kwi", avgPrice: 7950, listings: 195, sales: 1045, inventory: 98, demand: 82 },
    { month: "Maj", avgPrice: 8100, listings: 210, sales: 1030, inventory: 102, demand: 79 },
    { month: "Cze", avgPrice: 8200, listings: 225, sales: 1015, inventory: 105, demand: 77 },
  ],
  Poznań: [
    { month: "Sty", avgPrice: 7400, listings: 125, sales: 990, inventory: 78, demand: 73 },
    { month: "Lut", avgPrice: 7450, listings: 142, sales: 975, inventory: 82, demand: 75 },
    { month: "Mar", avgPrice: 7500, listings: 158, sales: 960, inventory: 85, demand: 77 },
    { month: "Kwi", avgPrice: 7550, listings: 175, sales: 945, inventory: 88, demand: 79 },
    { month: "Maj", avgPrice: 7650, listings: 190, sales: 930, inventory: 92, demand: 76 },
    { month: "Cze", avgPrice: 7800, listings: 205, sales: 915, inventory: 95, demand: 74 },
  ],
  Gdańsk: [
    { month: "Sty", avgPrice: 8100, listings: 165, sales: 1290, inventory: 98, demand: 79 },
    { month: "Lut", avgPrice: 8250, listings: 182, sales: 1275, inventory: 102, demand: 81 },
    { month: "Mar", avgPrice: 8400, listings: 198, sales: 1260, inventory: 105, demand: 83 },
    { month: "Kwi", avgPrice: 8550, listings: 215, sales: 1245, inventory: 108, demand: 85 },
    { month: "Maj", avgPrice: 8700, listings: 230, sales: 1230, inventory: 112, demand: 82 },
    { month: "Cze", avgPrice: 8900, listings: 245, sales: 1215, inventory: 115, demand: 80 },
  ],
  Szczecin: [
    { month: "Sty", avgPrice: 7200, listings: 110, sales: 850, inventory: 70, demand: 65 },
    { month: "Lut", avgPrice: 7250, listings: 120, sales: 860, inventory: 75, demand: 67 },
    { month: "Mar", avgPrice: 7300, listings: 130, sales: 870, inventory: 80, demand: 69 },
    { month: "Kwi", avgPrice: 7400, listings: 140, sales: 880, inventory: 85, demand: 71 },
    { month: "Maj", avgPrice: 7450, listings: 150, sales: 890, inventory: 90, demand: 68 },
    { month: "Cze", avgPrice: 7500, listings: 160, sales: 900, inventory: 95, demand: 66 },
  ],
  Bydgoszcz: [
    { month: "Sty", avgPrice: 6500, listings: 100, sales: 750, inventory: 60, demand: 60 },
    { month: "Lut", avgPrice: 6550, listings: 110, sales: 760, inventory: 65, demand: 62 },
    { month: "Mar", avgPrice: 6600, listings: 120, sales: 770, inventory: 70, demand: 64 },
    { month: "Kwi", avgPrice: 6700, listings: 130, sales: 780, inventory: 75, demand: 66 },
    { month: "Maj", avgPrice: 6750, listings: 140, sales: 790, inventory: 80, demand: 63 },
    { month: "Cze", avgPrice: 6800, listings: 150, sales: 800, inventory: 85, demand: 61 },
  ],
  Lublin: [
    { month: "Sty", avgPrice: 6900, listings: 90, sales: 650, inventory: 50, demand: 55 },
    { month: "Lut", avgPrice: 6950, listings: 100, sales: 660, inventory: 55, demand: 57 },
    { month: "Mar", avgPrice: 7000, listings: 110, sales: 670, inventory: 60, demand: 59 },
    { month: "Kwi", avgPrice: 7100, listings: 120, sales: 680, inventory: 65, demand: 61 },
    { month: "Maj", avgPrice: 7150, listings: 130, sales: 690, inventory: 70, demand: 58 },
    { month: "Cze", avgPrice: 7200, listings: 140, sales: 700, inventory: 75, demand: 56 },
  ],
  Katowice: [
    { month: "Sty", avgPrice: 7500, listings: 130, sales: 950, inventory: 80, demand: 70 },
    { month: "Lut", avgPrice: 7550, listings: 140, sales: 960, inventory: 85, demand: 72 },
    { month: "Mar", avgPrice: 7600, listings: 150, sales: 970, inventory: 90, demand: 74 },
    { month: "Kwi", avgPrice: 7700, listings: 160, sales: 980, inventory: 95, demand: 76 },
    { month: "Maj", avgPrice: 7750, listings: 170, sales: 990, inventory: 100, demand: 73 },
    { month: "Cze", avgPrice: 7800, listings: 180, sales: 1000, inventory: 105, demand: 71 },
  ],
}

// Rozszerzone dane zaawansowane dla większej liczby miast
export const advancedMetricsData: { [key: string]: any[] } = {
  Warszawa: [
    {
      month: "Sty",
      priceToIncome: 12.5,
      avgSaleTime: 45,
      vacancyRate: 3.2,
      roi: 4.8,
      mortgageDebt: 68.5,
      devActivity: 85,
    },
    {
      month: "Lut",
      priceToIncome: 12.7,
      avgSaleTime: 42,
      vacancyRate: 3.1,
      roi: 4.9,
      mortgageDebt: 69.2,
      devActivity: 87,
    },
    {
      month: "Mar",
      priceToIncome: 12.9,
      avgSaleTime: 40,
      vacancyRate: 2.9,
      roi: 5.1,
      mortgageDebt: 70.1,
      devActivity: 89,
    },
    {
      month: "Kwi",
      priceToIncome: 13.1,
      avgSaleTime: 38,
      vacancyRate: 2.8,
      roi: 5.2,
      mortgageDebt: 71.0,
      devActivity: 91,
    },
    {
      month: "Maj",
      priceToIncome: 13.3,
      avgSaleTime: 41,
      vacancyRate: 3.0,
      roi: 5.0,
      mortgageDebt: 70.8,
      devActivity: 88,
    },
    {
      month: "Cze",
      priceToIncome: 13.5,
      avgSaleTime: 43,
      vacancyRate: 3.2,
      roi: 4.8,
      mortgageDebt: 70.5,
      devActivity: 86,
    },
  ],
  Kraków: [
    {
      month: "Sty",
      priceToIncome: 11.2,
      avgSaleTime: 38,
      vacancyRate: 2.8,
      roi: 5.2,
      mortgageDebt: 65.2,
      devActivity: 82,
    },
    {
      month: "Lut",
      priceToIncome: 11.4,
      avgSaleTime: 36,
      vacancyRate: 2.7,
      roi: 5.3,
      mortgageDebt: 65.8,
      devActivity: 84,
    },
    {
      month: "Mar",
      priceToIncome: 11.6,
      avgSaleTime: 34,
      vacancyRate: 2.5,
      roi: 5.5,
      mortgageDebt: 66.5,
      devActivity: 86,
    },
    {
      month: "Kwi",
      priceToIncome: 11.8,
      avgSaleTime: 32,
      vacancyRate: 2.4,
      roi: 5.6,
      mortgageDebt: 67.2,
      devActivity: 88,
    },
    {
      month: "Maj",
      priceToIncome: 12.0,
      avgSaleTime: 35,
      vacancyRate: 2.6,
      roi: 5.4,
      mortgageDebt: 67.0,
      devActivity: 85,
    },
    {
      month: "Cze",
      priceToIncome: 12.2,
      avgSaleTime: 37,
      vacancyRate: 2.8,
      roi: 5.2,
      mortgageDebt: 66.8,
      devActivity: 83,
    },
  ],
  Łódź: [
    {
      month: "Sty",
      priceToIncome: 8.5,
      avgSaleTime: 55,
      vacancyRate: 4.5,
      roi: 6.2,
      mortgageDebt: 55.1,
      devActivity: 70,
    },
    {
      month: "Lut",
      priceToIncome: 8.6,
      avgSaleTime: 52,
      vacancyRate: 4.3,
      roi: 6.3,
      mortgageDebt: 55.8,
      devActivity: 72,
    },
    {
      month: "Mar",
      priceToIncome: 8.7,
      avgSaleTime: 50,
      vacancyRate: 4.1,
      roi: 6.5,
      mortgageDebt: 56.5,
      devActivity: 75,
    },
    {
      month: "Kwi",
      priceToIncome: 8.9,
      avgSaleTime: 48,
      vacancyRate: 4.0,
      roi: 6.6,
      mortgageDebt: 57.2,
      devActivity: 78,
    },
    {
      month: "Maj",
      priceToIncome: 9.0,
      avgSaleTime: 51,
      vacancyRate: 4.2,
      roi: 6.4,
      mortgageDebt: 57.0,
      devActivity: 76,
    },
    {
      month: "Cze",
      priceToIncome: 9.1,
      avgSaleTime: 53,
      vacancyRate: 4.4,
      roi: 6.3,
      mortgageDebt: 56.8,
      devActivity: 74,
    },
  ],
  Wrocław: [
    {
      month: "Sty",
      priceToIncome: 10.5,
      avgSaleTime: 48,
      vacancyRate: 3.8,
      roi: 5.8,
      mortgageDebt: 62.3,
      devActivity: 78,
    },
    {
      month: "Lut",
      priceToIncome: 10.6,
      avgSaleTime: 46,
      vacancyRate: 3.6,
      roi: 5.9,
      mortgageDebt: 63.0,
      devActivity: 80,
    },
    {
      month: "Mar",
      priceToIncome: 10.8,
      avgSaleTime: 44,
      vacancyRate: 3.4,
      roi: 6.1,
      mortgageDebt: 63.7,
      devActivity: 82,
    },
    {
      month: "Kwi",
      priceToIncome: 11.0,
      avgSaleTime: 42,
      vacancyRate: 3.2,
      roi: 6.2,
      mortgageDebt: 64.4,
      devActivity: 84,
    },
    {
      month: "Maj",
      priceToIncome: 11.1,
      avgSaleTime: 45,
      vacancyRate: 3.5,
      roi: 6.0,
      mortgageDebt: 64.2,
      devActivity: 81,
    },
    {
      month: "Cze",
      priceToIncome: 11.2,
      avgSaleTime: 47,
      vacancyRate: 3.7,
      roi: 5.9,
      mortgageDebt: 64.0,
      devActivity: 79,
    },
  ],
  Poznań: [
    {
      month: "Sty",
      priceToIncome: 9.8,
      avgSaleTime: 50,
      vacancyRate: 4.0,
      roi: 6.0,
      mortgageDebt: 60.1,
      devActivity: 75,
    },
    {
      month: "Lut",
      priceToIncome: 9.9,
      avgSaleTime: 48,
      vacancyRate: 3.8,
      roi: 6.1,
      mortgageDebt: 60.8,
      devActivity: 77,
    },
    {
      month: "Mar",
      priceToIncome: 10.0,
      avgSaleTime: 46,
      vacancyRate: 3.6,
      roi: 6.3,
      mortgageDebt: 61.5,
      devActivity: 79,
    },
    {
      month: "Kwi",
      priceToIncome: 10.2,
      avgSaleTime: 44,
      vacancyRate: 3.5,
      roi: 6.4,
      mortgageDebt: 62.2,
      devActivity: 81,
    },
    {
      month: "Maj",
      priceToIncome: 10.3,
      avgSaleTime: 47,
      vacancyRate: 3.7,
      roi: 6.2,
      mortgageDebt: 62.0,
      devActivity: 78,
    },
    {
      month: "Cze",
      priceToIncome: 10.4,
      avgSaleTime: 49,
      vacancyRate: 3.9,
      roi: 6.1,
      mortgageDebt: 61.8,
      devActivity: 76,
    },
  ],
  Gdańsk: [
    {
      month: "Sty",
      priceToIncome: 10.8,
      avgSaleTime: 35,
      vacancyRate: 2.5,
      roi: 5.5,
      mortgageDebt: 62.8,
      devActivity: 79,
    },
    {
      month: "Lut",
      priceToIncome: 11.0,
      avgSaleTime: 33,
      vacancyRate: 2.4,
      roi: 5.6,
      mortgageDebt: 63.4,
      devActivity: 81,
    },
    {
      month: "Mar",
      priceToIncome: 11.2,
      avgSaleTime: 31,
      vacancyRate: 2.2,
      roi: 5.8,
      mortgageDebt: 64.1,
      devActivity: 83,
    },
    {
      month: "Kwi",
      priceToIncome: 11.4,
      avgSaleTime: 29,
      vacancyRate: 2.1,
      roi: 5.9,
      mortgageDebt: 64.8,
      devActivity: 85,
    },
    {
      month: "Maj",
      priceToIncome: 11.6,
      avgSaleTime: 32,
      vacancyRate: 2.3,
      roi: 5.7,
      mortgageDebt: 64.6,
      devActivity: 82,
    },
    {
      month: "Cze",
      priceToIncome: 11.8,
      avgSaleTime: 34,
      vacancyRate: 2.5,
      roi: 5.5,
      mortgageDebt: 64.4,
      devActivity: 80,
    },
  ],
  Szczecin: [
    {
      month: "Sty",
      priceToIncome: 9.2,
      avgSaleTime: 60,
      vacancyRate: 5.0,
      roi: 5.5,
      mortgageDebt: 58.2,
      devActivity: 65,
    },
    {
      month: "Lut",
      priceToIncome: 9.3,
      avgSaleTime: 58,
      vacancyRate: 4.8,
      roi: 5.6,
      mortgageDebt: 58.8,
      devActivity: 67,
    },
    {
      month: "Mar",
      priceToIncome: 9.4,
      avgSaleTime: 56,
      vacancyRate: 4.6,
      roi: 5.8,
      mortgageDebt: 59.5,
      devActivity: 69,
    },
    {
      month: "Kwi",
      priceToIncome: 9.6,
      avgSaleTime: 54,
      vacancyRate: 4.5,
      roi: 5.9,
      mortgageDebt: 60.2,
      devActivity: 71,
    },
    {
      month: "Maj",
      priceToIncome: 9.7,
      avgSaleTime: 57,
      vacancyRate: 4.7,
      roi: 5.7,
      mortgageDebt: 60.0,
      devActivity: 68,
    },
    {
      month: "Cze",
      priceToIncome: 9.8,
      avgSaleTime: 59,
      vacancyRate: 4.9,
      roi: 5.6,
      mortgageDebt: 59.8,
      devActivity: 66,
    },
  ],
  Bydgoszcz: [
    {
      month: "Sty",
      priceToIncome: 8.0,
      avgSaleTime: 65,
      vacancyRate: 5.5,
      roi: 6.5,
      mortgageDebt: 52.1,
      devActivity: 60,
    },
    {
      month: "Lut",
      priceToIncome: 8.1,
      avgSaleTime: 62,
      vacancyRate: 5.3,
      roi: 6.6,
      mortgageDebt: 52.8,
      devActivity: 62,
    },
    {
      month: "Mar",
      priceToIncome: 8.2,
      avgSaleTime: 60,
      vacancyRate: 5.1,
      roi: 6.8,
      mortgageDebt: 53.5,
      devActivity: 64,
    },
    {
      month: "Kwi",
      priceToIncome: 8.4,
      avgSaleTime: 58,
      vacancyRate: 5.0,
      roi: 6.9,
      mortgageDebt: 54.2,
      devActivity: 66,
    },
    {
      month: "Maj",
      priceToIncome: 8.5,
      avgSaleTime: 61,
      vacancyRate: 5.2,
      roi: 6.7,
      mortgageDebt: 54.0,
      devActivity: 63,
    },
    {
      month: "Cze",
      priceToIncome: 8.6,
      avgSaleTime: 63,
      vacancyRate: 5.4,
      roi: 6.6,
      mortgageDebt: 53.8,
      devActivity: 61,
    },
  ],
  Lublin: [
    {
      month: "Sty",
      priceToIncome: 8.8,
      avgSaleTime: 62,
      vacancyRate: 5.2,
      roi: 6.0,
      mortgageDebt: 56.3,
      devActivity: 68,
    },
    {
      month: "Lut",
      priceToIncome: 8.9,
      avgSaleTime: 60,
      vacancyRate: 5.0,
      roi: 6.1,
      mortgageDebt: 57.0,
      devActivity: 70,
    },
    {
      month: "Mar",
      priceToIncome: 9.0,
      avgSaleTime: 58,
      vacancyRate: 4.8,
      roi: 6.3,
      mortgageDebt: 57.7,
      devActivity: 72,
    },
    {
      month: "Kwi",
      priceToIncome: 9.2,
      avgSaleTime: 56,
      vacancyRate: 4.7,
      roi: 6.4,
      mortgageDebt: 58.4,
      devActivity: 74,
    },
    {
      month: "Maj",
      priceToIncome: 9.3,
      avgSaleTime: 59,
      vacancyRate: 4.9,
      roi: 6.2,
      mortgageDebt: 58.2,
      devActivity: 71,
    },
    {
      month: "Cze",
      priceToIncome: 9.4,
      avgSaleTime: 61,
      vacancyRate: 5.1,
      roi: 6.1,
      mortgageDebt: 58.0,
      devActivity: 69,
    },
  ],
  Katowice: [
    {
      month: "Sty",
      priceToIncome: 9.5,
      avgSaleTime: 58,
      vacancyRate: 4.8,
      roi: 5.8,
      mortgageDebt: 59.4,
      devActivity: 72,
    },
    {
      month: "Lut",
      priceToIncome: 9.6,
      avgSaleTime: 56,
      vacancyRate: 4.6,
      roi: 5.9,
      mortgageDebt: 60.1,
      devActivity: 74,
    },
    {
      month: "Mar",
      priceToIncome: 9.7,
      avgSaleTime: 54,
      vacancyRate: 4.4,
      roi: 6.1,
      mortgageDebt: 60.8,
      devActivity: 76,
    },
    {
      month: "Kwi",
      priceToIncome: 9.9,
      avgSaleTime: 52,
      vacancyRate: 4.3,
      roi: 6.2,
      mortgageDebt: 61.5,
      devActivity: 78,
    },
    {
      month: "Maj",
      priceToIncome: 10.0,
      avgSaleTime: 55,
      vacancyRate: 4.5,
      roi: 6.0,
      mortgageDebt: 61.3,
      devActivity: 75,
    },
    {
      month: "Cze",
      priceToIncome: 10.1,
      avgSaleTime: 57,
      vacancyRate: 4.7,
      roi: 5.9,
      mortgageDebt: 61.1,
      devActivity: 73,
    },
  ],
}

// Rozszerzone dane inwestycyjne dla większej liczby miast
export const investmentMetrics: { [key: string]: any[] } = {
  Warszawa: [
    { month: "Sty", liquidityIndex: 78, seasonalityIndex: 65, speculationIndex: 42, maturityIndex: 85 },
    { month: "Lut", liquidityIndex: 80, seasonalityIndex: 68, speculationIndex: 45, maturityIndex: 86 },
    { month: "Mar", liquidityIndex: 82, seasonalityIndex: 72, speculationIndex: 48, maturityIndex: 87 },
    { month: "Kwi", liquidityIndex: 85, seasonalityIndex: 75, speculationIndex: 51, maturityIndex: 88 },
    { month: "Maj", liquidityIndex: 83, seasonalityIndex: 73, speculationIndex: 49, maturityIndex: 87 },
    { month: "Cze", liquidityIndex: 81, seasonalityIndex: 70, speculationIndex: 46, maturityIndex: 86 },
  ],
  Kraków: [
    { month: "Sty", liquidityIndex: 72, seasonalityIndex: 62, speculationIndex: 38, maturityIndex: 82 },
    { month: "Lut", liquidityIndex: 74, seasonalityIndex: 65, speculationIndex: 41, maturityIndex: 83 },
    { month: "Mar", liquidityIndex: 76, seasonalityIndex: 68, speculationIndex: 44, maturityIndex: 84 },
    { month: "Kwi", liquidityIndex: 78, seasonalityIndex: 71, speculationIndex: 47, maturityIndex: 85 },
    { month: "Maj", liquidityIndex: 76, seasonalityIndex: 69, speculationIndex: 45, maturityIndex: 84 },
    { month: "Cze", liquidityIndex: 74, seasonalityIndex: 66, speculationIndex: 42, maturityIndex: 83 },
  ],
  Łódź: [
    { month: "Sty", liquidityIndex: 60, seasonalityIndex: 55, speculationIndex: 55, maturityIndex: 70 },
    { month: "Lut", liquidityIndex: 62, seasonalityIndex: 58, speculationIndex: 58, maturityIndex: 71 },
    { month: "Mar", liquidityIndex: 65, seasonalityIndex: 62, speculationIndex: 61, maturityIndex: 72 },
    { month: "Kwi", liquidityIndex: 68, seasonalityIndex: 65, speculationIndex: 64, maturityIndex: 73 },
    { month: "Maj", liquidityIndex: 66, seasonalityIndex: 63, speculationIndex: 62, maturityIndex: 72 },
    { month: "Cze", liquidityIndex: 64, seasonalityIndex: 60, speculationIndex: 59, maturityIndex: 71 },
  ],
  Wrocław: [
    { month: "Sty", liquidityIndex: 70, seasonalityIndex: 60, speculationIndex: 40, maturityIndex: 80 },
    { month: "Lut", liquidityIndex: 72, seasonalityIndex: 63, speculationIndex: 43, maturityIndex: 81 },
    { month: "Mar", liquidityIndex: 74, seasonalityIndex: 66, speculationIndex: 46, maturityIndex: 82 },
    { month: "Kwi", liquidityIndex: 76, seasonalityIndex: 69, speculationIndex: 49, maturityIndex: 83 },
    { month: "Maj", liquidityIndex: 74, seasonalityIndex: 67, speculationIndex: 47, maturityIndex: 82 },
    { month: "Cze", liquidityIndex: 72, seasonalityIndex: 64, speculationIndex: 44, maturityIndex: 81 },
  ],
  Poznań: [
    { month: "Sty", liquidityIndex: 68, seasonalityIndex: 58, speculationIndex: 35, maturityIndex: 78 },
    { month: "Lut", liquidityIndex: 70, seasonalityIndex: 61, speculationIndex: 38, maturityIndex: 79 },
    { month: "Mar", liquidityIndex: 72, seasonalityIndex: 64, speculationIndex: 41, maturityIndex: 80 },
    { month: "Kwi", liquidityIndex: 74, seasonalityIndex: 67, speculationIndex: 44, maturityIndex: 81 },
    { month: "Maj", liquidityIndex: 72, seasonalityIndex: 65, speculationIndex: 42, maturityIndex: 80 },
    { month: "Cze", liquidityIndex: 70, seasonalityIndex: 62, speculationIndex: 39, maturityIndex: 79 },
  ],
  Gdańsk: [
    { month: "Sty", liquidityIndex: 75, seasonalityIndex: 70, speculationIndex: 45, maturityIndex: 83 },
    { month: "Lut", liquidityIndex: 77, seasonalityIndex: 73, speculationIndex: 48, maturityIndex: 84 },
    { month: "Mar", liquidityIndex: 79, seasonalityIndex: 76, speculationIndex: 51, maturityIndex: 85 },
    { month: "Kwi", liquidityIndex: 81, seasonalityIndex: 79, speculationIndex: 54, maturityIndex: 86 },
    { month: "Maj", liquidityIndex: 79, seasonalityIndex: 77, speculationIndex: 52, maturityIndex: 85 },
    { month: "Cze", liquidityIndex: 77, seasonalityIndex: 74, speculationIndex: 49, maturityIndex: 84 },
  ],
  Szczecin: [
    { month: "Sty", liquidityIndex: 65, seasonalityIndex: 55, speculationIndex: 30, maturityIndex: 75 },
    { month: "Lut", liquidityIndex: 67, seasonalityIndex: 58, speculationIndex: 33, maturityIndex: 76 },
    { month: "Mar", liquidityIndex: 69, seasonalityIndex: 61, speculationIndex: 36, maturityIndex: 77 },
    { month: "Kwi", liquidityIndex: 71, seasonalityIndex: 64, speculationIndex: 39, maturityIndex: 78 },
    { month: "Maj", liquidityIndex: 69, seasonalityIndex: 62, speculationIndex: 37, maturityIndex: 77 },
    { month: "Cze", liquidityIndex: 67, seasonalityIndex: 59, speculationIndex: 34, maturityIndex: 76 },
  ],
  Bydgoszcz: [
    { month: "Sty", liquidityIndex: 58, seasonalityIndex: 52, speculationIndex: 52, maturityIndex: 68 },
    { month: "Lut", liquidityIndex: 60, seasonalityIndex: 55, speculationIndex: 55, maturityIndex: 69 },
    { month: "Mar", liquidityIndex: 62, seasonalityIndex: 58, speculationIndex: 58, maturityIndex: 70 },
    { month: "Kwi", liquidityIndex: 64, seasonalityIndex: 61, speculationIndex: 61, maturityIndex: 71 },
    { month: "Maj", liquidityIndex: 62, seasonalityIndex: 59, speculationIndex: 59, maturityIndex: 70 },
    { month: "Cze", liquidityIndex: 60, seasonalityIndex: 56, speculationIndex: 56, maturityIndex: 69 },
  ],
  Lublin: [
    { month: "Sty", liquidityIndex: 62, seasonalityIndex: 56, speculationIndex: 32, maturityIndex: 72 },
    { month: "Lut", liquidityIndex: 64, seasonalityIndex: 59, speculationIndex: 35, maturityIndex: 73 },
    { month: "Mar", liquidityIndex: 66, seasonalityIndex: 62, speculationIndex: 38, maturityIndex: 74 },
    { month: "Kwi", liquidityIndex: 68, seasonalityIndex: 65, speculationIndex: 41, maturityIndex: 75 },
    { month: "Maj", liquidityIndex: 66, seasonalityIndex: 63, speculationIndex: 39, maturityIndex: 74 },
    { month: "Cze", liquidityIndex: 64, seasonalityIndex: 60, speculationIndex: 36, maturityIndex: 73 },
  ],
  Katowice: [
    { month: "Sty", liquidityIndex: 66, seasonalityIndex: 57, speculationIndex: 34, maturityIndex: 76 },
    { month: "Lut", liquidityIndex: 68, seasonalityIndex: 60, speculationIndex: 37, maturityIndex: 77 },
    { month: "Mar", liquidityIndex: 70, seasonalityIndex: 63, speculationIndex: 40, maturityIndex: 78 },
    { month: "Kwi", liquidityIndex: 72, seasonalityIndex: 66, speculationIndex: 43, maturityIndex: 79 },
    { month: "Maj", liquidityIndex: 70, seasonalityIndex: 64, speculationIndex: 41, maturityIndex: 78 },
    { month: "Cze", liquidityIndex: 68, seasonalityIndex: 61, speculationIndex: 38, maturityIndex: 77 },
  ],
}

// Dane do analizy ryzyka
export const riskAnalysisData: {
  [key: string]: { riskScore: number; factors: { volatility: number; bubbleRisk: number; economicStability: number } }
} = {
  Warszawa: { riskScore: 45, factors: { volatility: 50, bubbleRisk: 60, economicStability: 85 } },
  Kraków: { riskScore: 48, factors: { volatility: 55, bubbleRisk: 65, economicStability: 80 } },
  Łódź: { riskScore: 65, factors: { volatility: 70, bubbleRisk: 55, economicStability: 60 } },
  Wrocław: { riskScore: 52, factors: { volatility: 60, bubbleRisk: 62, economicStability: 75 } },
  Poznań: { riskScore: 55, factors: { volatility: 62, bubbleRisk: 58, economicStability: 72 } },
  Gdańsk: { riskScore: 50, factors: { volatility: 58, bubbleRisk: 68, economicStability: 78 } },
  Szczecin: { riskScore: 60, factors: { volatility: 65, bubbleRisk: 50, economicStability: 68 } },
  Bydgoszcz: { riskScore: 70, factors: { volatility: 75, bubbleRisk: 45, economicStability: 55 } },
  Lublin: { riskScore: 68, factors: { volatility: 72, bubbleRisk: 48, economicStability: 58 } },
  Katowice: { riskScore: 58, factors: { volatility: 63, bubbleRisk: 52, economicStability: 70 } },
}

export const correlationData: CorrelationData[] = [
  { metric: "Cena vs Dochody", correlation: 0.89, change: "+0.15" },
  { metric: "Czas Sprzedaży vs Cena", correlation: -0.76, change: "-0.08" },
  { metric: "Pustostany vs Popyt", correlation: -0.82, change: "-0.12" },
  { metric: "ROI vs Aktywność Dev.", correlation: 0.71, change: "+0.09" },
  { metric: "Migracja vs Popyt", correlation: 0.68, change: "+0.06" },
]
