// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using RealEstateAnalyzer.Infrastructure;

#nullable disable

namespace RealEstateAnalyzer.Infrastructure.Migrations
{
    [DbContext(typeof(DatabaseContext))]
    [Migration("20250811151327_Improve-Otodom-Housing-Listings-Entity")]
    partial class ImproveOtodomHousingListingsEntity
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.7")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("RealEstateAnalyzer.Domain.Entities.GusHousingListing", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<decimal>("AveragePricePerSqm")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("AverageTotalPrice")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("CityCode")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CityName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<long>("FlatsCompleted")
                        .HasColumnType("bigint");

                    b.Property<long>("FlatsSold")
                        .HasColumnType("bigint");

                    b.Property<decimal>("MedianPricePerSqm")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("TotalValueSold")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTimeOffset?>("UpdatedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("GusHousingListings", (string)null);
                });

            modelBuilder.Entity("RealEstateAnalyzer.Domain.Entities.OtodomHousingListing", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("DatePublished")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DateWebScraped")
                        .HasColumnType("datetime2");

                    b.Property<decimal>("FlatSize")
                        .HasColumnType("decimal(18,2)");

                    b.Property<bool>("IsDeveloperOffer")
                        .HasColumnType("bit");

                    b.Property<string>("MarketType")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("OfferId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<decimal>("PricePerSqm")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("PropertyType")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<decimal>("TotalPrice")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTimeOffset?>("UpdatedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Url")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("OfferId")
                        .IsUnique()
                        .HasDatabaseName("IX_OtodomHousingListings_OfferId");

                    b.ToTable("OtodomHousingListings", (string)null);
                });

            modelBuilder.Entity("RealEstateAnalyzer.Domain.Entities.GusHousingListing", b =>
                {
                    b.OwnsOne("RealEstateAnalyzer.Domain.ValueObjects.QuarterPeriod", "Period", b1 =>
                        {
                            b1.Property<Guid>("GusHousingListingId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<long>("Quarter")
                                .HasColumnType("bigint")
                                .HasColumnName("PeriodQuarter");

                            b1.Property<long>("Year")
                                .HasColumnType("bigint")
                                .HasColumnName("PeriodYear");

                            b1.HasKey("GusHousingListingId");

                            b1.ToTable("GusHousingListings");

                            b1.WithOwner()
                                .HasForeignKey("GusHousingListingId");
                        });

                    b.Navigation("Period")
                        .IsRequired();
                });

            modelBuilder.Entity("RealEstateAnalyzer.Domain.Entities.OtodomHousingListing", b =>
                {
                    b.OwnsOne("RealEstateAnalyzer.Domain.ValueObjects.Location", "Location", b1 =>
                        {
                            b1.Property<Guid>("OtodomHousingListingId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<string>("City")
                                .IsRequired()
                                .HasMaxLength(100)
                                .HasColumnType("nvarchar(100)");

                            b1.Property<string>("District")
                                .IsRequired()
                                .HasMaxLength(100)
                                .HasColumnType("nvarchar(100)");

                            b1.HasKey("OtodomHousingListingId");

                            b1.ToTable("OtodomHousingListings");

                            b1.WithOwner()
                                .HasForeignKey("OtodomHousingListingId");
                        });

                    b.Navigation("Location")
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
