import { DistrictData } from "@/models";

export const cityMapData: { [key: string]: DistrictData[] } = {
  Warszawa: [
    {
      district: "Śródmieście",
      averagePrice: 18500,
      properties: 350,
      trend: "up",
      change: "+9.1%",
    },
    {
      district: "Mokotów",
      averagePrice: 16200,
      properties: 580,
      trend: "up",
      change: "+11.5%",
    },
    {
      district: "Żoliborz",
      averagePrice: 15800,
      properties: 210,
      trend: "up",
      change: "+7.2%",
    },
    {
      district: "Praga-Północ",
      averagePrice: 13900,
      properties: 320,
      trend: "up",
      change: "+14.8%",
    },
    {
      district: "Wola",
      averagePrice: 15500,
      properties: 450,
      trend: "up",
      change: "+13.2%",
    },
    {
      district: "Ursynów",
      averagePrice: 14200,
      properties: 480,
      trend: "up",
      change: "+8.1%",
    },
    {
      district: "Wilanów",
      averagePrice: 17100,
      properties: 280,
      trend: "up",
      change: "+10.3%",
    },
    {
      district: "Białołęka",
      averagePrice: 11500,
      properties: 650,
      trend: "down",
      change: "-1.2%",
    },
  ],
  Kraków: [
    {
      district: "Stare Miasto",
      averagePrice: 16800,
      properties: 280,
      trend: "up",
      change: "+10.8%",
    },
    {
      district: "Kazimierz",
      averagePrice: 15500,
      properties: 210,
      trend: "up",
      change: "+9.1%",
    },
    {
      district: "Podgórze",
      averagePrice: 13200,
      properties: 450,
      trend: "up",
      change: "+11.7%",
    },
    {
      district: "Krowodrza",
      averagePrice: 13800,
      properties: 390,
      trend: "up",
      change: "+8.4%",
    },
    {
      district: "Nowa Huta",
      averagePrice: 10500,
      properties: 550,
      trend: "up",
      change: "+9.9%",
    },
    {
      district: "Bronowice",
      averagePrice: 12800,
      properties: 310,
      trend: "down",
      change: "-0.5%",
    },
    {
      district: "Grzegórzki",
      averagePrice: 14500,
      properties: 250,
      trend: "up",
      change: "+12.1%",
    },
  ],
  Gdańsk: [
    {
      district: "Śródmieście",
      averagePrice: 15200,
      properties: 290,
      trend: "up",
      change: "+14.8%",
    },
    {
      district: "Wrzeszcz",
      averagePrice: 13800,
      properties: 380,
      trend: "up",
      change: "+11.9%",
    },
    {
      district: "Oliwa",
      averagePrice: 14500,
      properties: 220,
      trend: "up",
      change: "+10.2%",
    },
    {
      district: "Zaspa",
      averagePrice: 12200,
      properties: 310,
      trend: "up",
      change: "+8.1%",
    },
    {
      district: "Przymorze",
      averagePrice: 12800,
      properties: 420,
      trend: "up",
      change: "+9.5%",
    },
    {
      district: "Chełm",
      averagePrice: 10800,
      properties: 350,
      trend: "down",
      change: "-1.8%",
    },
    {
      district: "Jelitkowo",
      averagePrice: 16500,
      properties: 150,
      trend: "up",
      change: "+18.2%",
    },
  ],
  Wrocław: [
    {
      district: "Stare Miasto",
      averagePrice: 14800,
      properties: 310,
      trend: "up",
      change: "+9.5%",
    },
    {
      district: "Krzyki",
      averagePrice: 13500,
      properties: 520,
      trend: "up",
      change: "+10.1%",
    },
    {
      district: "Psie Pole",
      averagePrice: 11800,
      properties: 480,
      trend: "up",
      change: "+7.8%",
    },
    {
      district: "Fabryczna",
      averagePrice: 12200,
      properties: 450,
      trend: "up",
      change: "+8.3%",
    },
  ],
  Poznań: [
    {
      district: "Stare Miasto",
      averagePrice: 13200,
      properties: 340,
      trend: "up",
      change: "+8.8%",
    },
    {
      district: "Grunwald",
      averagePrice: 11900,
      properties: 460,
      trend: "up",
      change: "+9.2%",
    },
    {
      district: "Jeżyce",
      averagePrice: 12500,
      properties: 380,
      trend: "up",
      change: "+9.9%",
    },
    {
      district: "Wilda",
      averagePrice: 11500,
      properties: 320,
      trend: "up",
      change: "+7.5%",
    },
  ],
  Łódź: [
    {
      district: "Śródmieście",
      averagePrice: 9200,
      properties: 410,
      trend: "up",
      change: "+6.1%",
    },
    {
      district: "Bałuty",
      averagePrice: 8500,
      properties: 550,
      trend: "up",
      change: "+5.8%",
    },
    {
      district: "Polesie",
      averagePrice: 8700,
      properties: 480,
      trend: "up",
      change: "+6.3%",
    },
  ],
  Szczecin: [
    {
      district: "Śródmieście",
      averagePrice: 9800,
      properties: 380,
      trend: "up",
      change: "+7.1%",
    },
    {
      district: "Prawobrzeże",
      averagePrice: 8900,
      properties: 420,
      trend: "up",
      change: "+6.5%",
    },
    {
      district: "Zachód",
      averagePrice: 9100,
      properties: 350,
      trend: "up",
      change: "+6.8%",
    },
  ],
  Bydgoszcz: [
    {
      district: "Śródmieście",
      averagePrice: 8200,
      properties: 310,
      trend: "up",
      change: "+5.5%",
    },
    {
      district: "Fordon",
      averagePrice: 7500,
      properties: 450,
      trend: "up",
      change: "+5.1%",
    },
    {
      district: "Błonie",
      averagePrice: 7800,
      properties: 280,
      trend: "up",
      change: "+5.3%",
    },
  ],
  Lublin: [
    {
      district: "Śródmieście",
      averagePrice: 9500,
      properties: 330,
      trend: "up",
      change: "+7.2%",
    },
    {
      district: "Czechów",
      averagePrice: 8800,
      properties: 400,
      trend: "up",
      change: "+6.9%",
    },
    {
      district: "LSM",
      averagePrice: 8600,
      properties: 370,
      trend: "up",
      change: "+6.5%",
    },
  ],
  Katowice: [
    {
      district: "Śródmieście",
      averagePrice: 9400,
      properties: 360,
      trend: "up",
      change: "+6.2%",
    },
    {
      district: "Ligota-Panewniki",
      averagePrice: 8700,
      properties: 430,
      trend: "up",
      change: "+5.9%",
    },
    {
      district: "Brynów",
      averagePrice: 8900,
      properties: 390,
      trend: "up",
      change: "+6.0%",
    },
  ],
  Białystok: [
    {
      district: "Centrum",
      averagePrice: 8500,
      properties: 300,
      trend: "up",
      change: "+6.8%",
    },
    {
      district: "Sienkiewicza",
      averagePrice: 8200,
      properties: 280,
      trend: "up",
      change: "+6.5%",
    },
    {
      district: "Nowe Miasto",
      averagePrice: 7900,
      properties: 350,
      trend: "up",
      change: "+6.1%",
    },
  ],
  Kielce: [
    {
      district: "Centrum",
      averagePrice: 7800,
      properties: 250,
      trend: "up",
      change: "+5.8%",
    },
    {
      district: "Ślichowice",
      averagePrice: 7200,
      properties: 320,
      trend: "up",
      change: "+5.5%",
    },
  ],
  Olsztyn: [
    {
      district: "Śródmieście",
      averagePrice: 8100,
      properties: 270,
      trend: "up",
      change: "+6.3%",
    },
    {
      district: "Pojezierze",
      averagePrice: 7600,
      properties: 340,
      trend: "up",
      change: "+5.9%",
    },
  ],
  Rzeszów: [
    {
      district: "Nowe Miasto",
      averagePrice: 8900,
      properties: 310,
      trend: "up",
      change: "+7.5%",
    },
    {
      district: "Drabinianka",
      averagePrice: 8500,
      properties: 380,
      trend: "up",
      change: "+7.1%",
    },
  ],
  Opole: [
    {
      district: "Śródmieście",
      averagePrice: 7900,
      properties: 260,
      trend: "up",
      change: "+6.1%",
    },
    {
      district: "Zaodrze",
      averagePrice: 7400,
      properties: 330,
      trend: "up",
      change: "+5.7%",
    },
  ],
  "Zielona Góra": [
    {
      district: "Centrum",
      averagePrice: 7600,
      properties: 290,
      trend: "up",
      change: "+6.4%",
    },
    {
      district: "Nowe Miasto",
      averagePrice: 7100,
      properties: 360,
      trend: "up",
      change: "+5.9%",
    },
  ],
};

export const elegantColors = [
  "#5470c6",
  "#91cc75",
  "#fac858",
  "#ee6666",
  "#73c0de",
  "#3ba272",
  "#fc8452",
  "#9a60b4",
  "#ea7ccc",
];
