<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net9.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
	<TreatWarningsAsErrors>true</TreatWarningsAsErrors>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="HtmlAgilityPack" Version="1.12.2" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\RealEstateAnalyzer.WebScrapping.Domain\RealEstateAnalyzer.WebScraping.Domain.csproj" />
  </ItemGroup>

</Project>
