import { FilterConfig } from "@/models";

export const cityComparisonFilterConfig: FilterConfig[] = [
  {
    id: "cities",
    type: "multiselect",
    label: "Wybierz miasta do porównania",
    placeholder: "Wybierz miasta",
    defaultValue: ["Warszawa", "Kraków", "Gdańsk"],
    options: [
      { value: "Warszawa", label: "Warszawa" },
      { value: "Kraków", label: "Kraków" },
      { value: "Gdańsk", label: "Gdańsk" },
      { value: "Wrocław", label: "Wrocław" },
      { value: "Poznań", label: "Poznań" },
      { value: "Łódź", label: "Łódź" },
      { value: "Szczecin", label: "Szczecin" },
      { value: "Lublin", label: "Lublin" },
      { value: "Katowice", label: "Katowice" },
      { value: "Białystok", label: "Białystok" },
    ],
  },
  {
    id: "trend",
    type: "select",
    label: "Trend cenowy",
    placeholder: "Wybierz trend",
    options: [
      { value: "wzrostowy", label: "Wzrostowy" },
      { value: "stabilny", label: "Stabilny" },
      { value: "spadkowy", label: "Spadkowy" },
    ],
  },
  {
    id: "marketShareRange",
    type: "range",
    label: "Udział w rynku (%)",
    min: 0,
    max: 25,
    step: 1,
    defaultValue: [0, 25],
    options: [],
  },
  {
    id: "populationRange",
    type: "range",
    label: "Populacja (tys.)",
    min: 50,
    max: 2000,
    step: 50,
    defaultValue: [50, 2000],
    options: [],
  },
  {
    id: "growthRange",
    type: "range",
    label: "Wzrost cen (%)",
    min: 0,
    max: 20,
    step: 0.5,
    defaultValue: [0, 20],
    options: [],
  },
  {
    id: "priceRange",
    type: "range",
    label: "Zakres cen (PLN/m²)",
    min: 8000,
    max: 18000,
    step: 500,
    defaultValue: [8000, 18000],
    options: [],
  },
];

export const citiesData = [
  {
    id: 1,
    name: "Warszawa",
    voivodeship: "mazowieckie",
    trend: "wzrostowy",
    marketShare: 22.5,
    population: 1790,
    averagePrice: 17500,
    growth: 8.5,
    totalTransactions: 2340,
  },
  {
    id: 2,
    name: "Kraków",
    voivodeship: "malopolskie",
    trend: "wzrostowy",
    marketShare: 15.2,
    population: 780,
    averagePrice: 15800,
    growth: 12.3,
    totalTransactions: 1890,
  },
  {
    id: 3,
    name: "Gdańsk",
    voivodeship: "pomorskie",
    trend: "stabilny",
    marketShare: 8.7,
    population: 470,
    averagePrice: 14900,
    growth: 15.7,
    totalTransactions: 1456,
  },
  {
    id: 4,
    name: "Wrocław",
    voivodeship: "dolnoslaskie",
    trend: "wzrostowy",
    marketShare: 12.1,
    population: 640,
    averagePrice: 13200,
    growth: 9.8,
    totalTransactions: 1680,
  },
  {
    id: 5,
    name: "Poznań",
    voivodeship: "wielkopolskie",
    trend: "stabilny",
    marketShare: 9.8,
    population: 540,
    averagePrice: 11800,
    growth: 7.2,
    totalTransactions: 1320,
  },
  {
    id: 6,
    name: "Łódź",
    voivodeship: "lodzkie",
    trend: "spadkowy",
    marketShare: 5.4,
    population: 680,
    averagePrice: 8800,
    growth: 5.8,
    totalTransactions: 890,
  },
  {
    id: 7,
    name: "Szczecin",
    voivodeship: "zachodniopomorskie",
    trend: "stabilny",
    marketShare: 4.2,
    population: 400,
    averagePrice: 9200,
    growth: 8.9,
    totalTransactions: 720,
  },
  {
    id: 8,
    name: "Katowice",
    voivodeship: "slaskie",
    trend: "wzrostowy",
    marketShare: 7.3,
    population: 290,
    averagePrice: 9100,
    growth: 4.3,
    totalTransactions: 980,
  },
  {
    id: 9,
    name: "Lublin",
    voivodeship: "lubelskie",
    trend: "wzrostowy",
    marketShare: 6.1,
    population: 370,
    averagePrice: 9500,
    growth: 6.7,
    totalTransactions: 850,
  },
  {
    id: 10,
    name: "Białystok",
    voivodeship: "podlaskie",
    trend: "stabilny",
    marketShare: 3.9,
    population: 320,
    averagePrice: 8200,
    growth: 7.1,
    totalTransactions: 640,
  },
];

export const comparisonChartOptions = {
  chart: {
    type: "bubble",
    height: 400,
  },
  title: {
    text: "Porównanie miast - cena vs udział w rynku vs populacja",
  },
  xAxis: {
    title: {
      text: "Średnia cena (zł)",
    },
  },
  yAxis: {
    title: {
      text: "Udział w rynku (%)",
    },
  },
  series: [
    {
      name: "Miasta",
      data: citiesData.map((city) => ({
        x: city.averagePrice,
        y: city.marketShare,
        z: city.population / 10,
        name: city.name,
        population: city.population,
        trend: city.trend,
      })),
    },
  ],
};

export const extendedPriceHistoryData = [
  {
    month: "Sty",
    Warszawa: 16000,
    Kraków: 14200,
    Gdańsk: 13100,
    Wrocław: 11800,
    Poznań: 10400,
    Łódź: 8500,
    Szczecin: 8900,
    Lublin: 9200,
    Katowice: 8800,
    Białystok: 7900,
  },
  {
    month: "Cze",
    Warszawa: 17500,
    Kraków: 15800,
    Gdańsk: 14900,
    Wrocław: 13200,
    Poznań: 11800,
    Łódź: 8800,
    Szczecin: 9200,
    Lublin: 9500,
    Katowice: 9100,
    Białystok: 8200,
  },
]

export const cityColors: { [key: string]: string } = {
  Warszawa: "#228be6",
  Kraków: "#0ca678",
  Gdańsk: "#f76707",
  Wrocław: "#e64980",
  Poznań: "#7048e8",
  Łódź: "#15aabf",
  Szczecin: "#5c940d",
  Lublin: "#f59f00",
  Katowice: "#d6336c",
  Białystok: "#4c6ef5",
}
