version: "3.9"

services:
  redis:
    image: redis:7-alpine
    command: ["redis-server", "--appendonly", "yes"]  
    ports:
      - "6379:6379"            # dostęp z hosta (opcjonalnie)
    volumes:
      - redis-data:/data
    restart: unless-stopped

  app:
    build: .
    depends_on:
      - redis
    environment:
      - REDIS_CONNECTION=redis:6379
    ports:
      - "5000:80"             
