name: .NET - Build & Test

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v4
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 9.0.x
    - name: Restore dependencies
      run: dotnet restore rea_api/rea_api.sln
    - name: Build
      run: dotnet build rea_api/rea_api.sln --no-restore
    - name: Test
      run: dotnet test rea_api/rea_api.sln --no-build --verbosity normal --collect:"XPlat Code Coverage" --results-directory coverage

    - name: Report coverage summary
      run: |
        dotnet tool install --global dotnet-reportgenerator-globaltool
        reportgenerator -reports:coverage/**/coverage.cobertura.xml -targetdir:coverage-report -reporttypes:HtmlSummary
      env:
        PATH: $PATH:/github/home/.dotnet/tools

    - name: Upload coverage artifact
      uses: actions/upload-artifact@v4
      with:
        name: coverage-html
        path: coverage-report
